/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.Diagnostics.CodeAnalysis;

namespace Juna.SKS.Package.Website.Models
{ 
    [ExcludeFromCodeCoverage]
    public class ParcelInput 
    { 
        public float Weight { get; set; }


        public string RecipientName { get; set; }

        public string RecipientStreet { get; set; }

        public string RecipientPostalCode { get; set; }

        public string RecipientCity { get; set; }

        public string RecipientCountry { get; set; }


        public string SenderName { get; set; }

        public string SenderStreet { get; set; }

        public string SenderPostalCode { get; set; }

        public string SenderCity { get; set; }

        public string SenderCountry { get; set; }

    }
}
